name: integration-test

on:
  push:
    branches: [ test-cicd-2 ]
  pull_request:
    branches: [ master ]

jobs:
  test-cryptogen:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm ci
    - run: npm run build:console
    - run: ./cicd/test_script/cryptogen.sh

  test-ca:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm ci
    - run: npm run build:console
    - run: ./cicd/test_script/ca.sh

